---
- name: add docker audit
  become: 'yes'
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/docker.rules
    mode: 0600
    owner: root
    group: root
  notify:
    - restart auditd
  tags:
    - docker
    - auditd
...
