---
- name: create nginx directory
  become: 'yes'
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - nginx

- name: add nginx config
  become: 'yes'
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  tags:
    - nginx

- name: add nginx default website config
  become: 'yes'
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
    owner: root
    group: root
  tags:
    - nginx

- name: create webserver root directory
  become: 'yes'
  file:
    path: /var/www/{{ ansible_hostname }}
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - nginx

- name: add skeleton index.html
  become: 'yes'
  template:
    src: index.html.j2
    dest: /var/www/{{ ansible_hostname }}/index.html
    mode: 0644
    owner: root
    group: root
  tags:
    - nginx

- name: nginx container
  become: 'yes'
  docker_container:
    name: nginx
    image: konstruktoid/nginx
    state: started
    restart: 'yes'
    ports:
      - "{{ nginx_bind_port }}:{{ nginx_bind_port }}"
    cap_drop: all
    capabilities:
      - chown
      - dac_override
      - net_bind_service
      - setgid
      - setuid
    ulimits:
      - nofile:8032:16064
    volumes:
      - /etc/nginx/:/etc/nginx/:ro
      - /var/www/{{ ansible_hostname }}:/var/www/{{ ansible_hostname }}:ro
    pull: 'yes'
    restart_policy: on-failure
    restart_retries: 3
    hostname: "{{ ansible_nodename }}"
  tags:
    - docker_container
    - nginx
...
