---
- name: only allow traffic from balancers
  become: 'yes'
  ufw:
    rule: allow
    src: "{{ hostvars[item]['ansible_host'] }}"
    port: "{{ nginx_bind_port|int }}"
    proto: tcp
    comment: ansible managed
  with_items:
    - "{{ groups['loadbalancer'] }}"
  tags:
    - ufw
    - nginx
...
